name: "update-cloud-spanner-emulator-version"
on:
  workflow_dispatch:
  schedule:
    # every Monday at around 3 am pacific/10 am UTC
    - cron: "0 10 * * 1"
env:
  GOPROXY: https://proxy.golang.org
  GO_VERSION: '1.20.2'
permissions:
  contents: read

jobs:
  bump-cloud-spanner-emulator-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{env.GO_VERSION}}
          cache: true
          cache-dependency-path: ./go.sum
      - name: Bump cloud-spanner-emulator version
        id: bumpCloudSpannerEmulator
        run: |
          make update-cloud-spanner-emulator-version
          # The following is to support multiline with GITHUB_OUTPUT, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.bumpCloudSpannerEmulator.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: bump cloud-spanner-emulator version
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: auto_bump_cloud_spanner_emulator_version
          push-to-fork: minikube-bot/minikube
          base: master
          delete-branch: true
          title: 'bump cloud-spanner-emulator version'
          labels: ok-to-test
          body: |
            cloud-spanner-emulator project released a [new version](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator),

            This PR was auto-generated by `make update-cloud-spanner-emulator-version` using [update-cloud-spanner-emulator-version.yml](https://github.com/kubernetes/minikube/tree/master/.github/workflows/update-cloud-spanner-emulator-version.yml) CI Workflow.
